services:
  - type: web
    name: hmcsnacks-app
    runtime: docker
    repo: https://github.com/hetchauhan-cloud/HMCSnacks
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    autoDeploy: true
